name: Auto Deploy

on:
  push:
    branches:
      - storybook

jobs:
  storybook:
    name: Storybook
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
#          FOLDER: storybook-static
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: docs
          BRANCH: gh-pages
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
