name: Auto Deploy

on:
  push:
    branches:
      - storybook

jobs:
  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Build
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
#          FOLDER: storybook-static
          FOLDER: storybook-static
          BRANCH: gh-pages
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
