name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get Pnpm Store
        id: pnpm-store
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup Pnpm Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Run Test
        run: pnpm run test
